(+ 1 2 3)
((lambda (a b) (+ a b)) 1 2)
()
(set f (lambda (a b) (if spooky (pprint b a "spooky doggo" spooky) (or (local spooky 101) (pprint a b "non spooky doggo" spooky)))))
(f 3 6)
(f)
(pprint "even spookier" spooky)
(f 4 2)
(f)
(+ 0 six)
(* (+ (+ 1 3) 2) 2 3)
(/ 120 2 2 2)
(0)
(+ 1 2 (0) 3)
(- 3 (6) 9)
(* (+ (+ (1) 3) 2) 2 3)
(/ 120 2 (2) 2)
(/ 1 0)
(if (> 1 2) "true" "false")
(if (< 1 2) "true" "false")
(if (> 2 2) "true" "false")
(if (< 2 2) "true" "false")
(if (>= 1 2) "true" "false")
(if (<= 1 2) "true" "false")
(if (>= 2 2) "true" "false")
(if (<= 2 2) "true" "false")
(if (= 1 1) "true" "false")
(if (= 2 1) "true" "false")
(if (= 1 2) "true" "false")
(if (= "doggo" "doggo") "true" "false")
(if (= "doggo" "gattar") "true" "false")
